# Generated by Django 5.0.1 on 2024-02-07 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_docs_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs',
            name='author',
        ),
    ]
